[package]
name = "authentication"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.14.2"
tonic-reflection = "0.14.2"
tonic-prost = "0.14.2"
tonic-web = "0.14.2"
prost = "0.14.1"
tokio-stream = "0.1.17"
axum = "0.8.8"
jsonwebtoken = "9.3.0"
digest = "0.10.7"
serde_json = "1.0.147"
anyhow = "1.0.100"
thiserror = "2.0.17"
dotenvy = "0.15.7"
aes-gcm = "0.10.3"
base64 = "0.22"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = { version = "0.18", features = ["derive"] }
subtle = "2.6"

tokio = {version = "1.48.0", features = ["macros", "rt-multi-thread"]}
diesel = { version = "2.2.0", features = ["postgres", "uuid", "chrono", "r2d2"] }
uuid = {version = "1.19.0", features = ["v4", "serde"]}
serde = {version = "1.0.228", features = ["derive"]}
chrono = {version = "0.4.42", features = ["serde"]}
pbkdf2 = {version = "0.12.2", features = ["simple"]}
sha2 = "0.10.8"
hex = "0.4.3"
rand = "0.8.5"
totp-rs = "5.6.0"
base32 = "0.5.1"
resend-rs = "0.19.0"
http = "1.4.0"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["cors"] }
cookie = "0.18"
prost-types = "0.14.3"

[build-dependencies]
tonic-prost-build = "0.14.2"

