apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U "$POSTGRES_USER"; do
                sleep 2
              done
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: authentication-secret
                  key: POSTGRES_USER

      containers:
        - name: authentication
          image: ghcr.io/lootopia-org/core:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: authentication-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentication-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: authentication-secret
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
      resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
