apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: authentication
          image: ghcr.io/lootopia-org/authentication:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
          envFrom:
            - secretRef:
                name: authentication-secret
          resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "100m"
                memory: "512Mi"
