apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-service.yaml
  - postgres-stateful.yaml
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: authentication

